server.port: 8484

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql.init.mode: always
  datasource:
    #url: jdbc:h2:~/nklcb
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #username: sa
    #password:
    url: jdbc:mysql://localhost:3306/welcome?characterEncoding=UTF-8&serverTimezone=UTC
    username: 100minha
    password: rapael4785


  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
        #dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

#Live Reload 기능 활성화
  devtools:livereload:enabled: true
  resources:static-locations: file:src/main/resources/static/
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
